export const HEADER_ALIASES = {
  partCode: [
    "part code",
    "part number",
    "parts number",
    "part no",
    "part no.",
    "article",
    "artikuly",
    "artikul",
    "артикул",
    "номер запчаста",
    "номер запчасти",
    "мнемонический код",
    "助记码",
    "图号",
    "型号",
    "code",
    "qism kodi",
    "qism code",
    "qism raqami",
    "qism nomeri",
    "kod",
    "零件编号",
    "产品编号",
  ],
  partName: ["name", "part name", "product name", "nomi", "qism nomi", "название", "имя", "产品名称", "名称"],
  categoryName: ["category", "kategoriya", "分类"],
  brand: ["brand", "brend", "бренд", "品牌"],
  type: ["type", "quality", "turi", "sifat", "оригинал", "бренд", "质量", "类型"],
  purchasePriceCny: [
    "purchase price",
    "purchase price cny",
    "price",
    "narx",
    "цена",
    "цена cny",
    "narxi",
    "xarid narxi",
    "xarid narxi ¥",
    "xarid narxi (¥)",
    "unit price",
    "unit price cny",
    "价格",
    "单价",
    "单价（人民币）",
  ],
  wholesalePriceCny: ["wholesale price", "wholesale price cny", "ulgurji narx", "ulgurji narx (¥)"],
  sellingPriceCny: ["selling price", "selling price cny", "sale price", "sotuv narxi", "sotuv narxi (¥)"],
  supplierName: ["supplier", "supplier name", "seller", "sotuvchi", "ta'minotchi", "taminotchi", "yetkazib beruvchi", "продавец", "供应商", "卖家"],
  quantity: ["qty", "quantity", "order", "miqdor", "soni", "заказ", "数量"],
  note: ["note", "notes", "izoh", "eslatma", "备注"],
} as const;

export const TYPE_ALIASES: Record<string, string> = {
  original: "original",
  orginal: "original",
  oem: "oem",
  copy: "copy",
  kopiya: "copy",
  aftermarket: "aftermarket",
  analog: "aftermarket",
  analogue: "aftermarket",
  "原厂": "original",
  "副厂": "copy",
  "代用": "aftermarket",
};

export type HeaderField = keyof typeof HEADER_ALIASES;
